// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
	schema: 'prisma/schema.prisma',
	migrations: {
		path: 'prisma/migrations',
		// seed: 'npx --loader ts-node prisma/seed.ts',
		seed: 'npx tsx prisma/seed.ts', // استخدام tsx بدلاً من ts-node
	},
	datasource: {
		// هذا الرابط يستخدمه Prisma فقط أثناء تنفيذ npx prisma migrate
		url: process.env.DATABASE_URL!,
	},
});
